# Generated by Django 2.1.2 on 2018-10-31 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
