# Generated by Django 2.1.3 on 2018-11-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_id', models.CharField(max_length=200)),
                ('investor_id', models.CharField(max_length=200)),
                ('bid_price', models.IntegerField()),
                ('no_of_shares', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
