# Generated by Django 2.1.3 on 2018-11-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181103_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='symbol',
            field=models.CharField(default='AAAA', max_length=4),
            preserve_default=False,
        ),
    ]
